services:
  nextjs-cache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-cache-app
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=Asia/Bangkok
    restart: unless-stopped
    volumes:
      - ./nextjs-cache-data:/app/.next/cache
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge
